apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n

resources:
  - namespace.yaml
  - rbac.yaml
  - pvc.yaml
  - n8n-deployment.yaml
  - service.yaml
  - certificate.yaml
  - ingressroute.yaml
  - sealed-secrets/postgres-credentials-sealed.yaml
  - sealed-secrets/n8n-encryption-key-sealed.yaml
