apiVersion: v1
kind: Service
metadata:
  name: navidrome-service
  namespace: navidrome
  labels:
    app: navidrome
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 4533
    targetPort: http
    protocol: TCP
  selector:
    app: navidrome
