apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: filebrowser
  namespace: filebrowser
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`files.feto.dev`)
      kind: Rule
      services:
        - name: filebrowser
          port: 80
  tls:
    secretName: filebrowser-tls
