apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-services

resources:
  - router-service.yaml
  - router-certificate.yaml
  - router-ingressroute.yaml
  - homeassistant-service.yaml
  - homeassistant-certificate.yaml
  - homeassistant-ingressroute.yaml
  - ttyd-service.yaml
  - ttyd-certificate.yaml
  - ttyd-ingressroute.yaml