---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gork         # gork.thiemo.click
  - n8n          # n8n.thiemo.click
  - external-services  # External LAN services
  - navidrome    # navidrome.feto.dev
  - filebrowser  # files.feto.dev
  - tandoor      # rezepte.thiemo.click
