---
apiVersion: v1
kind: Service
metadata:
  name: tandoor-service
  namespace: tandoor
  labels:
    app.kubernetes.io/name: tandoor
spec:
  type: ClusterIP
  selector:
    app: tandoor
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
