apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  # SMB CSI Driver v1.15.0 installation manifests
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/v1.15.0/deploy/rbac-csi-smb.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/v1.15.0/deploy/csi-smb-driver.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/v1.15.0/deploy/csi-smb-controller.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/v1.15.0/deploy/csi-smb-node.yaml
